# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:13.12
    working_directory: /home/circleci/docs
    steps:
      - checkout
      - run: |
          if [[ "$(git show -s --format=%B | head -n 1)" == "autogen"* ]]; then
            circleci-agent step halt
          fi
      - run: git config --global user.email "aeneas@ory.sh"
      - run: git config --global user.name "aeneasr"
      - run: npm i
      - run: npm run format
      - run: |
          git add -A
          (git commit -a -m "autogen: build docs from $CIRCLE_SHA1" && git push origin HEAD:master) || true
      - run: npm run build
      - run: |
          git clone git@github.com:ory/web.git ../web
          rm -rf ../web/generated/docs/ecosystem/* ../web/generated/docs/ecosystem/*
          cp -R ./build/* ../web/generated/docs/ecosystem/
          cd ../web
          git add -A
          git status
          git commit -a -m "docs: Bump to $CIRCLE_SHA1" --allow-empty
          git push origin HEAD:master

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /master/
