# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:9-browsers
    working_directory: /home/circleci/docs
    environment:
      - GITBOOK_DIR: /home/circleci/docs/.gitbook
      - VERSION: latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: git config --global user.email "hi@ory.am"
      - run: git config --global user.name "ORY Continuous Integration"
      - run: "git clone https://arekkas:$DOCS_TOKEN_PUSH@github.com/ory/ory-am.git ../ory-am"
      - run: "VERSION=${CIRCLE_TAG:-latest}; mkdir -p ../ory-am/docs/guides/$VERSION/ || exit 0"
      - run: "VERSION=${CIRCLE_TAG:-latest}; mkdir -p ../ory-am/docs/apis/$VERSION/ || exit 0"
      - run: "cp -R ./build/faq/* ../ory-am/docs/faq/"
      - run: "rm -rf ../ory-am/docs/latest/*"
      - run: "VERSION=${CIRCLE_TAG:-latest}; cp -R ./build/guides/* ../ory-am/docs/guides/$VERSION/"
      - run: "VERSION=${CIRCLE_TAG:-latest}; cp -R ./apis/* ../ory-am/docs/apis/$VERSION/"
      - run: "(VERSION=${CIRCLE_TAG:-latest}; cd ../ory-am && git add -A && git commit -a -m \"docs: Updates documentation version $VERSION\" && git push origin) || exit 0"

workflows:
  version: 2
  "publish":
    jobs:
      - publish:
          filters:
            branches:
              only: master
            tags:
              only: /.*/